
var slideshow ={
		
		init: function(){
			
			var div_el='listing_carousel';
			var tmp = Math.round(Math.random()*10000);  SS_up_ele='slideshow'+tmp; eval("var SS_trSpeed"+tmp+"='5000';"); eval("var slideshow"+tmp+" = {id:'slideshow"+tmp+"',trSpeed:'5000',trSSid:''};");
			document.write('<script type=\"text\/javascript\">');
			 document.write('  var site_root = \'http:\/\/synd.trulia.com\/\';');
			 document.write('function perform_slideshow_meta(el, dir,data)');
			 document.write('{');
			 document.write('    var slideshow_window = el;');
			 document.write('');
			 document.write('    if (!slideshow_window)');
			 document.write('        return false;');
			 document.write('');
			 document.write('    var previous_page_num_el = document.getElementById(slideshow_window.id + \'_previous_page_num\'),');
			 document.write('    next_page_num_el = document.getElementById(slideshow_window.id + \'_next_page_num\');');
			 document.write('');
			 document.write('    if (!previous_page_num_el || !next_page_num_el)');
			 document.write('        return false;');
			 document.write('');
			 document.write('    var previous_btn = document.getElementById(slideshow_window.id + \'_previous\'),');
			 document.write('    next_btn = document.getElementById(slideshow_window.id + \'_next\');');
			 document.write('    play_btn = document.getElementById(slideshow_window.id + \'_play\');');
			 document.write('');
			 document.write('  ');
			 document.write('    if (dir == -1)');
			 document.write('    {');
			 document.write('        var page_requested = previous_page_num_el.innerHTML;');
			 document.write('');
			 document.write('        if (page_requested==\"\" || !page_requested)');
			 document.write('        {');
			 document.write('            if (previous_btn)');
			 document.write('                w_add_class(previous_btn, \'SS-first-button-disabled\');');
			 document.write('');
			 document.write('        }');
			 document.write(' ');
			 document.write('');
			 document.write('    }');
			 document.write('    else');
			 document.write('    {');
			 document.write('        page_requested = next_page_num_el.innerHTML;');
			 document.write('        if (page_requested==\"\" || !page_requested)');
			 document.write('        {');
			 document.write('            if (next_btn)');
			 document.write('            {');
			 document.write('                w_add_class(next_btn, \'SS-second-button-disabled\');');
			 document.write('                w_remove_class(next_btn, \'trSlideShowNext\');');
			 document.write('');
			 document.write('            }');
			 document.write('        }');
			 document.write('');
			 document.write('    }');
			 document.write('  ');
			 document.write('    if (previous_btn)');
			 document.write('    {');
			 document.write('    ');
			 document.write('        if (!data.l_previous_page_num)');
			 document.write('            w_add_class(previous_btn, \'SS-first-button-disabled\');');
			 document.write('        else');
			 document.write('        {');
			 document.write('            w_remove_class(previous_btn, \'SS-first-button-disabled\');');
			 document.write('            w_add_class(previous_btn, \'trSlideShowBack\');');
			 document.write('        }');
			 document.write('    }');
			 document.write('');
			 document.write('    if (next_btn)');
			 document.write('    {');
			 document.write('        if (!data.l_next_page_num)');
			 document.write('        {');
			 document.write('            w_add_class(next_btn, \'SS-second-button-disabled\');');
			 document.write('            w_remove_class(next_btn, \'trSlideShowNext\');');
			 document.write('        }');
			 document.write('        else');
			 document.write('            w_remove_class(next_btn, \'SS-second-button-disabled\');');
			 document.write('    }');
			 document.write('');
			 document.write('');
			 document.write('}');
			 document.write('');
			 document.write('\/**');
			 document.write('Removes a class from an element');
			 document.write('@param  el            element whose class to remove. Can be the id or the actual element');
			 document.write('@param  w_remove_class  class to be removed');
			 document.write('');
			 document.write('@return boolean');
			 document.write('**\/');
			 document.write('function w_remove_class(el, removed_class)');
			 document.write('{');
			 document.write('    if (typeof(removed_class) == \'undefined\')');
			 document.write('        return false;');
			 document.write('');
			 document.write('    ');
			 document.write('    if(typeof(el) != \'object\')');
			 document.write('        el = document.getElementById(el);');
			 document.write('');
			 document.write('    ');
			 document.write('    if (!el)');
			 document.write('        return false;');
			 document.write('');
			 document.write('    var class_array = el.className.split(\' \');');
			 document.write('    var class_changed = false;');
			 document.write('');
			 document.write('    for (var i in class_array)');
			 document.write('    {');
			 document.write('        if (class_array[i] == removed_class)');
			 document.write('        {');
			 document.write('            ');
			 document.write('            class_array.splice(i, 1);');
			 document.write('            class_changed = true;');
			 document.write('        }');
			 document.write('    }');
			 document.write('');
			 document.write('    if (class_changed)');
			 document.write('        el.className = class_array.join(\' \');');
			 document.write('');
			 document.write('    return class_changed;');
			 document.write('}');
			 document.write('');
			 document.write('\/**');
			 document.write('Checks if an element has a class');
			 document.write('@param  el              element to check. Can be the id or the actual element');
			 document.write('@param  searched_class  class to checked');
			 document.write('');
			 document.write('@return boolean');
			 document.write('**\/');
			 document.write('function w_has_class(el, searched_class)');
			 document.write('{');
			 document.write(' ');
			 document.write('    if (typeof(searched_class) == \'undefined\' || !searched_class)');
			 document.write('        return false;');
			 document.write('');
			 document.write('    ');
			 document.write('    if(typeof(el) != \'object\')');
			 document.write('        el = document.getElementById(el);');
			 document.write('');
			 document.write('    if (!el)');
			 document.write('        return false;');
			 document.write('');
			 document.write('    var class_array = el.className.split(\' \');');
			 document.write('');
			 document.write('    for(var i in class_array)');
			 document.write('    {');
			 document.write('        if (class_array[i] == searched_class)');
			 document.write('            return true;');
			 document.write('    }');
			 document.write('    return false;');
			 document.write('}');
			 document.write('');
			 document.write('\/**');
			 document.write('Adds a class to an element');
			 document.write('@param  el            element whose class to add. Can be the id or the actual element');
			 document.write('@param  w_add_class     class to be added');
			 document.write('');
			 document.write('@return boolean');
			 document.write('**\/');
			 document.write('function w_add_class(el, added_class)');
			 document.write('{');
			 document.write('');
			 document.write('    if (typeof(added_class) == \'undefined\')');
			 document.write('        return false;');
			 document.write('');
			 document.write('    ');
			 document.write('    if(typeof(el) != \'object\')');
			 document.write('        el = document.getElementById(el);');
			 document.write('');
			 document.write('    ');
			 document.write('    if (!el || w_has_class(el, added_class))');
			 document.write('        return false;');
			 document.write('');
			 document.write('    el.className = el.className + \' \' + added_class;');
			 document.write('');
			 document.write('    return true;');
			 document.write('}');
			 document.write('\/*Finds computed width and heigth of an element');
			 document.write('@param  el      required, element. Can be id or actual element');
			 document.write('@return array   {height: x, width:y}');
			 document.write('**\/');
			 document.write('function get_object_dimensions(el)');
			 document.write('{');
			 document.write('    ');
			 document.write('    if(typeof(el)!=\'object\')');
			 document.write('        el = xb_get_element(el);');
			 document.write('    if (!el)');
			 document.write('        return {');
			 document.write('            \'height\': null,');
			 document.write('            \'width\': null');
			 document.write('        };');
			 document.write('');
			 document.write('    var changed_display = false;');
			 document.write('');
			 document.write('    ');
			 document.write('    if (el.style.display == \'none\')');
			 document.write('    {');
			 document.write('        el.style.display = \'\';');
			 document.write('        changed_display = true;');
			 document.write('    }');
			 document.write('');
			 document.write('    var objWidth = 0;');
			 document.write('    var objHeight = 0;');
			 document.write('    if (el.offsetWidth || el.offsetWidth === 0)');
			 document.write('    {');
			 document.write('        objWidth = el.offsetWidth;');
			 document.write('        objHeight = el.offsetHeight;');
			 document.write('    }');
			 document.write('    else if (document.defaultView.getComputedStyle)');
			 document.write('    {');
			 document.write('        objHeight = document.defaultView.getComputedStyle(el, \"\").getPropertyValue(\"height\");');
			 document.write('        objWidth = document.defaultView.getComputedStyle(el, \"\").getPropertyValue(\"width\");');
			 document.write('    }');
			 document.write('    else if (el.clip)');
			 document.write('    {');
			 document.write('        objWidth = el.clip.width;');
			 document.write('        objHeight = el.clip.height;');
			 document.write('    }');
			 document.write('');
			 document.write('    if (changed_display)');
			 document.write('        el.style.display = \'none\';');
			 document.write('');
			 document.write('    return {');
			 document.write('        \'height\':objHeight,');
			 document.write('        \'width\':objWidth');
			 document.write('    };');
			 document.write('}');
			 document.write('function set_opac(el, opac, dis, dim_to_set)');
			 document.write('{');
			 document.write('');
			 document.write('    if (!el)');
			 document.write('        return false;');
			 document.write('');
			 document.write('    ');
			 document.write('    if (is_IE6() && (typeof(el.style.width) == \'undefined\' || !el.style.width) && (typeof(el.style.height) == \'undefined\' || !el.style.height))');
			 document.write('    {');
			 document.write('        var dim = get_object_dimensions(el);');
			 document.write('        var dim_set = false;');
			 document.write('    ');
			 document.write('        if (dim_to_set == \'height\' && dim.height)');
			 document.write('        {');
			 document.write('            el.style.height = dim.height;');
			 document.write('            dim_set = true;');
			 document.write('        }');
			 document.write('        else if (dim_to_set == \'width\' && dim.width)');
			 document.write('        {');
			 document.write('            el.style.width = dim.width;');
			 document.write('            dim_set = true;');
			 document.write('        }');
			 document.write('    ');
			 document.write('        if (!dim_set)');
			 document.write('        {');
			 document.write('    ');
			 document.write('            if (dim.height === 0)');
			 document.write('            {');
			 document.write('                if (dim.width === 0)');
			 document.write('                    el.style.height = \'\';');
			 document.write('                else');
			 document.write('                    el.style.width = dim.width;');
			 document.write('            }');
			 document.write('            else');
			 document.write('                el.style.height = dim.height;');
			 document.write('        }');
			 document.write('    }');
			 document.write('');
			 document.write('    ');
			 document.write('    if (typeof(opac) == \'undefined\' || opac >= 100)');
			 document.write('    {');
			 document.write('        moz_opac = \'\';');
			 document.write('        ie_opac = \'\';');
			 document.write('    }');
			 document.write('    else if (opac <= 0)');
			 document.write('    {');
			 document.write('        moz_opac = 0;');
			 document.write('        ie_opac = 0;');
			 document.write('    }');
			 document.write('    else');
			 document.write('    {');
			 document.write('        moz_opac = opac \/ 100;');
			 document.write('        ie_opac = \'alpha(opacity=\' + opac + \')\';');
			 document.write('    }');
			 document.write('');
			 document.write('    ');
			 document.write('    el.style.opacity = moz_opac;');
			 document.write('    el.style.MozOpacity = moz_opac;');
			 document.write('    el.style.KhtmlOpacity = moz_opac;');
			 document.write('    el.style.filter = ie_opac;');
			 document.write('');
			 document.write('    ');
			 document.write('    if (opac <= 0)');
			 document.write('    {');
			 document.write('        if (typeof(dis) == \'undefined\' || (dis != \'none\' && dis != \'block\' && dis != \'inline\'))');
			 document.write('            el.style.display = \'\';');
			 document.write('        else');
			 document.write('            el.style.display = dis;');
			 document.write('    }');
			 document.write('');
			 document.write('    return true;');
			 document.write('}');
			 document.write('function is_IE()');
			 document.write('{');
			 document.write('    return (navigator.appName.indexOf(\"Microsoft Internet Explorer\") > -1);');
			 document.write('};');
			 document.write('function is_IE6()');
			 document.write('{');
			 document.write('    return (navigator.appName.indexOf(\"Microsoft Internet Explorer\") > -1 && !window.XMLHttpRequest)');
			 document.write('};');
			 document.write('function is_IE7()');
			 document.write('{');
			 document.write('    return (navigator.appName.indexOf(\"Microsoft Internet Explorer\") > -1 && window.XMLHttpRequest)');
			 document.write('};');
			 document.write('function is_Chrome()');
			 document.write('{');
			 document.write('    return navigator.userAgent.toLowerCase().indexOf(\'chrome\') > -1;');
			 document.write('};');
			 document.write('function is_Firefox()');
			 document.write('{');
			 document.write('    return navigator.userAgent.toLowerCase().indexOf(\"firefox\") > -1;');
			 document.write('};');
			 document.write('function is_Safari()');
			 document.write('{');
			 document.write('    return navigator.userAgent.toLowerCase().indexOf(\"safari\") >  -1;');
			 document.write('};');
			 document.write('function trSlideShowNext(slideshow_window,dir,prop_type,search_url,row_num,rand_id,tpp,type)');
			 document.write('{');
			 document.write('    if(dir==-1)');
			 document.write('    {');
			 document.write('        page_requested=document.getElementById(rand_id.id+\"_previous_page_num\").innerHTML;');
			 document.write('        if(!page_requested)');
			 document.write('            return false;');
			 document.write('    }');
			 document.write('    else');
			 document.write('    {');
			 document.write('        page_requested=document.getElementById(rand_id.id+\"_next_page_num\").innerHTML;');
			 document.write('        if(!page_requested)');
			 document.write('        {');
			 document.write('      ');
			 document.write('            trSlideShow();');
			 document.write('            return false;');
			 document.write('        }');
			 document.write('      ');
			 document.write('    }');
			 document.write('');
			 document.write('    set_opac(document.getElementById(rand_id.id), 30);');
			 document.write('    document.getElementById(\"SS_dir\").innerHTML=dir;');
			 document.write('    var lpr=(dir==1)?document.getElementById(rand_id.id+\"_next_page_num\").innerHTML:document.getElementById(rand_id.id+\"_previous_page_num\").innerHTML;');
			 document.write('    var tag=document.getElementById(\"SS_scripts\");');
			 document.write('    var sc=document.createElement(\"script\");');
			 document.write('    sc.src=site_root+\"q_get_carousel_items.php?lpr=\"+lpr+\"&surl=\"+search_url+\"&bpid=&ppid=-1&propt=\"+prop_type+\"&track_code=Details&callback=1&row_num=\"+row_num+\"&tpp=\"+tpp+\"&uid=\"+rand_id.id+\"&carousel_type=\"+type;');
			 document.write('    tag.appendChild(sc);');
			 document.write('}');
			 document.write('function SS_turn_over(data,uid)');
			 document.write('{');
			 document.write('    ');
			 document.write('    o_el=document.getElementById(uid.id);');
			 document.write('    var header_paginate=o_el.id+\"_header_paginate\";');
			 document.write('    o_el.innerHTML=data.new_html_items;');
			 document.write('    document.getElementById(o_el.id+\"_next_page_num\").innerHTML=data.l_next_page_num;');
			 document.write('    document.getElementById(o_el.id+\"_previous_page_num\").innerHTML=data.l_previous_page_num;');
			 document.write('    if(document.getElementById(header_paginate))');
			 document.write('        document.getElementById(header_paginate).innerHTML=data.paging_string;');
			 document.write('    perform_slideshow_meta(o_el, document.getElementById(\"SS_dir\").innerHTML,data);');
			 document.write('    set_opac(o_el, 100);');
			 document.write('}');
			 document.write('function rand_id()');
			 document.write('{');
			 document.write('    return Math.round(Math.random()*10000);');
			 document.write('}');
			 document.write('function trSlideShow(rand_id)');
			 document.write('{');
			 document.write('');
			 document.write('  if(rand_id.trSSid!=\'\' && typeof(rand_id.trSSid)!=\'undefined\')');
			 document.write('  {');
			 document.write('');
			 document.write('    clearInterval(rand_id.trSSid);');
			 document.write('    rand_id.trSSid=\'\';');
			 document.write('    if(w_has_class(rand_id.id+\"_play\", \'SS-pause-button\'))');
			 document.write('      w_remove_class(rand_id.id+\"_play\", \'SS-pause-button\');');
			 document.write('    w_add_class(rand_id.id+\"_play\", \'SS-play-button\');');
			 document.write('');
			 document.write('  }');
			 document.write('  else');
			 document.write('  {');
			 document.write('    if(typeof(rand_id.id)!=\'undefined\')');
			 document.write('      eval(\"rand_id.trSSid=trSlideShowPlay\"+rand_id.id+\"(rand_id.trSpeed);\");');
			 document.write('');
			 document.write('    if(w_has_class(rand_id.id+\"_play\", \'SS-play-button\'))');
			 document.write('      w_remove_class(rand_id.id+\"_play\", \'SS-play-button\');');
			 document.write('    w_add_class(rand_id.id+\"_play\", \'SS-pause-button\');');
			 document.write('');
			 document.write('');
			 document.write('  }');
			 document.write('}');
			 document.write('<\/script>');
			 document.write('<link rel=\"stylesheet\" type=\"text\/css\" href=\"http:\/\/css.trulia-cdn.com\/css\/slideshow_widget.css?v=E07_13\">');
			 document.write('<style type=\"text\/css\">');
			 document.write('  #tSlideShow .trPrice{display:inline;}');
			 document.write('  #tSlideShow .trBedBath{display:inline;}');
			 document.write('<\/style>');
			 document.write('<script>');
			 document.write(' eval( \"function trSlideShowPlay\"+SS_up_ele+\"(trSpeed){return setInterval(\\\"trSlideShowNext(\'listing_carousel\',1,\'for sale\',\'NY%2FNew_York%2F\',\'1\',\"+SS_up_ele+\",\'\',\'450\')\\\",trSpeed);  }\");');
			 document.write('<\/script>');
			 document.write('<script>document.write(\"<style>#\"+SS_up_ele+\"_previous{cursor:pointer;background:transparent url(http:\/\/static.trulia-cdn.com\/images\/tools\/slideshow_imagesheet.png) no-repeat scroll 0 0px;float:left;position:absolute;bottom:9px;right:45px;} #\"+SS_up_ele+\"_next{cursor:pointer;background:transparent url(http:\/\/static.trulia-cdn.com\/images\/tools\/slideshow_imagesheet.png) no-repeat scroll 0 -20px;float:right;bottom:9px; right:5px; position:absolute;}#\"+SS_up_ele+\"_play{cursor:pointer;background:transparent url(http:\/\/static.trulia-cdn.com\/images\/tools\/slideshow_imagesheet.png) no-repeat scroll 0 -60px;float:left;position:absolute;bottom:9px;right:25px;} <\/style>\");<\/script>');
			 document.write('<div>');
			 document.write('  <div id=\"tSlideShowC\">');
			 document.write('    <h3 class=\"tSlideShowH\">');
			 document.write('      <div class=\"tTitle\">New York Homes for sale<\/div>');
			 document.write('    <\/h3>');
			 document.write('    <div class=\"tSlideShowB\">');
			 document.write('      <div class=\"tSlideShowPr\">');
			 document.write('        <div class=\'tSlideShowSh\'>');
			 document.write('          <script type=\"text\/javascript\">document.write(\"<span style=\'display:block; position:absolute; left:13px; bottom:11px;font-weight:normal;line-height:14px;\' id=\'\"+SS_up_ele+\"_header_paginate\'>1 of 13,158<\/span>\");<\/script>');
			 document.write('          <script>document.write(\"<span id=\'\"+SS_up_ele+\"_previous\' onclick=\\\"trSlideShowNext(\'listing_carousel\',-1,\'for sale\',\'NY%2FNew_York%2F\',\'1\',\"+SS_up_ele+\",\'\',\'450\');\\\"  class=\'SS-first-button-disabled\'>\");<\/script>');
			 document.write('          <input type=\"button\" name=\"Previous Page\"  class=\"\" style=\"background-color:transparent;border:none;width:17px;height:20px;margin-right:2px;\"\/>');
			 document.write('          <\/span>');
			 document.write('          <script>document.write(\"<span id=\'\"+SS_up_ele+\"_play\' onclick=\\\"trSlideShow(\"+SS_up_ele+\");\\\"  class=\'SS-play-button\'>\");<\/script>');
			 document.write('          <input type=\"button\" name=\"Play SlideShow\"  class=\"\" style=\"background-color:transparent;border:none;width:17px;height:20px;margin-right:2px;\" \/>');
			 document.write('          <\/span>');
			 document.write('          <script>document.write(\"<span id=\'\"+SS_up_ele+\"_next\'  onclick=\\\"trSlideShowNext(\'listing_carousel\',1,\'for sale\',\'NY%2FNew_York%2F\',\'1\',\"+SS_up_ele+\",\'\',\'450\');\\\"  class=\'trSlideShowNext\'\");<\/script>');
			 document.write('');
			 document.write('          <input type=\"button\" name=\"Next Page\"  style=\"background-color:transparent;border:none;width:17px;height:20px;margin-right:2px;\" \/>');
			 document.write('          <\/span>');
			 document.write('        <\/div>');
			 document.write('        <div style=\"overflow:hidden; margin:0px 30px 0px 58px;\">');
			 document.write('          <script>document.write(\"<ol id=\'\"+SS_up_ele+\"\'>\");<\/script>');
			 document.write('                  <li><div class=\"slideshow_listing\">');
			 document.write('            <div style=\"width:320px; height:240px;\"><a class=\"tslideshowImg\" style=\"width:320px; height:240px;\" href=\"http:\/\/www.trulia.com\/syndication\/?id=AATS0002&url=http:\/\/www.trulia.com\/property\/3075803866--217th-St-New-York-NY-11411\" target=\"_blank\"><img');
			 document.write('                                                                            src=\"http:\/\/thumbs.trulia.com\/pictures\/thumbs_3\/ps.39\/a\/e\/1\/c\/picture-uh=a2f9f4ed22fdffae6fe47b6238fefb0-ps=ae1cea47c1b89818635114368ab195.jpg\"');
			 document.write('                                                                            alt=\" 217th Street, New York NY\"');
			 document.write('                                                                            border=\"0\"\/><\/a>');
			 document.write('            <\/div>');
			 document.write('          <a class=\"slideshow_prop_address\"');
			 document.write('            href=\"http:\/\/www.trulia.com\/syndication\/?id=AATS0003&url=http:\/\/www.trulia.com\/property\/3075803866--217th-St-New-York-NY-11411\"');
			 document.write('            alt=\" 217th Street, New York NY\"');
			 document.write('            title=\" 217th Street, New York NY\" target=\"_blank\"> 217th Street, New York NY<\/a>');
			 document.write('');
			 document.write('          <p class=\"trPrice\">$509,000<\/p>');
			 document.write('');
			 document.write('          <p class=\"trBedBath\">5 br&nbsp; 4 ba<\/p>');
			 document.write('        <\/div><\/li>');
			 document.write(' ');
			 document.write('');
			 document.write('          <\/ol>');
			 document.write('        <\/div>');
			 document.write('');
			 document.write('      <\/div>');
			 document.write('    <\/div>');
			 document.write('    <div class=\"tSlideShowZ\">');
			 document.write('      <div><img src=\"http:\/\/origin-tracking.trulia.com\/trackingPixel.gif?id=widget_truliaslideshow&impSource=www\" alt=\"\" width=\"1\" height=\"1\" \/><\/div>');
			 document.write('      <script> document.write(\'<span class=\"hidden\" id=\"\'+SS_up_ele+\'_previous_page_num\"><\/span> <span class=\"hidden\" id=\"\'+SS_up_ele+\'_next_page_num\">2<\/span> <span class=\"hidden\" id=\"SS_dir\"><\/span>\');<\/script>');
			 document.write('      <div id=\"SS_scripts\" class=\"hidden\"><\/div>');
			 document.write('    <\/div>');
			 document.write('    <div id=\"tSlideShowL\"><a target=\"_top\" href=\"http:\/\/www.trulia.com\/syndication\/?id=AATS0001&url=http:\/\/www.trulia.com\/\" style=\"position:absolute; right:-5px;\"><img height=\"30\" border=\"0\" width=\"70\" src=\"http:\/\/static.trulia-cdn.com\/images\/logos\/trulia-logo.png\"\/><\/a><\/div>');
			 document.write('  <\/div>');
			 document.write('<\/div>');
			 document.write('');
			 document.write('');
			
			
			
		}
		
		
		
}
